### ISSUE TITLE
Can Apple reject this on app store ? 

### ISSUE THREAD

**Issue by Souness11** [kapralos/arpmac#2]
Im considering using this example for my application. I want to know if apple can reject my app because of using this example. Thanks for answer.

**Comment by kapralos** [comment]
I used this code in production a couple of years ago and Apple did not reject the app. There are no explicit prohibitions - at least I couldn't find one. However, Apple is unpredictable, keep this in mind.

**Comment by Souness11** [comment]
Maybe ipv6 support which is must have on iOS 9

**Comment by kapralos** [comment]
Good point. Frankly, I don't have the answer and I think no one will until he try to submit a similar code.

**Comment by Souness11** [comment]
Is there any chance that you can support ipv6 on this example ? I should try to submit app next month and than I will reply if its work or not.

**Comment by kapralos** [comment]
A new protocol NDP (Neighbor Discovery Protocol) is used for ipv6 instead of ARP: https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/NetworkingConcepts/PacketRoutingandDelivery/PacketRoutingandDelivery.html

I don't think I'll add ipv6 support anytime soon.
